import tkinter as tk
 
baseGround = tk.Tk()

baseGround.geometry('500x50')
 
baseGround.title('FxxkSHARPApps')

def btn_click():    
    label1 = tk.Label(baseGround, text='Selected Uninstall').place(x=290,y=15)
    print('selected Uninstall.')
    import subprocess
    
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.settingsaquosusefull')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.scshocapture2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'sharp.jp.android.makersiteappli')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.iwnnime.ml')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.shframecapture')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.karadamate')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.pseudlock.helper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.emopar')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.sharpdatabackup')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.scrollauto')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.shrobodockservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.SHWirelessOutput')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mb')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mc')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.LockWeatherWidget')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.startuptutorial_ps')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.friendlink')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.service.hikarieffect')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.shlivewallpaper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.emopa.overlayservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.emopa.systemservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.wallpaper3d')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'uninstall', '-k', '--user', '0', 'jp.co.sharp.android.lockwallpaperchanger')
    subprocess.call(cmd)
    print('All_Done')
    label1 = tk.Label(baseGround, text='All Done              ').place(x=290,y=15)
    
def btn2_click():
    label1 = tk.Label(baseGround, text='Selected Install   ').place(x=290,y=15)
    print('selected Install.')
    import subprocess
    
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.settingsaquosusefull')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.scshocapture2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'sharp.jp.android.makersiteappli')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.iwnnime.ml')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.shframecapture')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.karadamate')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.pseudlock.helper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.emopar')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.emopar.internalcontent')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.emopar.internalcontent2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.sharpdatabackup')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.scrollauto')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.shrobodockservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.SHWirelessOutput')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.shinstructionmanual02mb')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.shinstructionmanual02mc')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.LockWeatherWidget')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.startuptutorial_ps')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.friendlink')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.service.hikarieffect')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.shlivewallpaper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.emopa.overlayservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.emopa.systemservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.wallpaper3d')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'cmd', 'package', 'install-existing', 'jp.co.sharp.android.lockwallpaperchanger')
    subprocess.call(cmd)
    print('All_Done')
    label1 = tk.Label(baseGround, text='All Done              ').place(x=290,y=15)

def btn3_click():
    label1 = tk.Label(baseGround, text='Selected Disable  ').place(x=290,y=15)
    print('selected Disable.')
    import subprocess
    
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.settingsaquosusefull')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.scshocapture2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'sharp.jp.android.makersiteappli')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.iwnnime.ml')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.shframecapture')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.karadamate')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.pseudlock.helper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.emopar')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.sharpdatabackup')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.scrollauto')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.shrobodockservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.SHWirelessOutput')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mb')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mc')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.LockWeatherWidget')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.startuptutorial_ps')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.friendlink')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.service.hikarieffect')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.shlivewallpaper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.emopa.overlayservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.emopa.systemservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.wallpaper3d')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'disable-user', '--user', '0', 'jp.co.sharp.android.lockwallpaperchanger')
    subprocess.call(cmd)
    print('All_Done')
    label1 = tk.Label(baseGround, text='All Done              ').place(x=290,y=15)

def btn4_click():
    label1 = tk.Label(baseGround, text='Selected Enable   ').place(x=290,y=15)
    print('selected Enable.')
    import subprocess
           
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.settingsaquosusefull')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.scshocapture2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'sharp.jp.android.makersiteappli')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.iwnnime.ml')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.shframecapture')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.karadamate')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.pseudlock.helper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.emopar')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.emopar.internalcontent2')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.sharpdatabackup')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.scrollauto')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.shrobodockservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.SHWirelessOutput')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mb')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.shinstructionmanual02mc')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.LockWeatherWidget')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.startuptutorial_ps')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.friendlink')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.service.hikarieffect')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.shlivewallpaper')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.emopa.overlayservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.emopa.systemservice')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.wallpaper3d')
    subprocess.call(cmd)
    cmd = ('adb', 'shell', 'pm', 'enable', '--user', '0', 'jp.co.sharp.android.lockwallpaperchanger') 
    subprocess.call(cmd)
    print('All_Done')
    label1 = tk.Label(baseGround, text='All Done              ').place(x=290,y=15)
    
button = tk.Button(
    baseGround, text='Uninstall', command=btn_click).place(x= 10, y=10)

button2 = tk.Button(
    baseGround, text='Install', command=btn2_click).place(x= 90, y=10)
 
button3 = tk.Button(
    baseGround, text='Disable', command=btn3_click).place(x= 155, y=10)

button4 = tk.Button(
    baseGround, text='Enable', command=btn4_click).place(x= 225, y=10)
    
baseGround.mainloop()
